### ISSUE TITLE
verify all of these forms are proper nouns

### ISSUE THREAD

**Issue by jtauber** [seumasjeltzz/LinguaeGraecaePerSeIllustrata#10]
(from chapters 2–6)
```
Αγγ
Ἀλέξιον
Ἀλέξιος
Ἀλεξίου
Ἀντιοχεία
Ἀντιοχείᾳ
Ἀντιόχειαν
Ἀντιοχείας
Γηργόριος
Γηργόριους
Γρη
Γρηγόριον
Γρηγόριος
Γρηγορίου
Γρηγόριου
Γρηγορίῳ
Γρηγρορίου
Γρηρόριος
Δημήρτιος
Δημήτριε
Δημήτριον
Δημήτριος
Δημητρίου
Δικαιόπολις
Εἰρήνη
Εἰρήνης
Εὐγενία
Εὐγενίᾳ
Εὐγενίαν
Εὐγενίας
Ζεύς
Ἡρακλείδης
Ἱεροσόλυμα
Ἰησοῦς
Κεφαλαῖον
Κεφάλαιον
Κίλισσα
Κιλίσσης
Μακ
Μακάριον
Μακάριος
Μαρ
Μάρκος
Ξανθίᾳ
Ξανθίας
Πιερίᾳ
Ῥωμαϊκός
Ῥώμην
Σελεύκεια
Σελεύκειαν
Σελεύκιαν
Σελευκίας
Σοσίαν
Σοφία
Σοφίας
Σύρα
Συριακαί
Συριακή
Συριακός
Συρίας
Σως
Σωσία
Σωσίαν
Σωσίας
Σωσίου
Σωφία
Σωφίαν
Τρο
Τροχίλε
Τροχίλον
Τροχίλος
Χριστιανῶν
Χριστός
Χριστοῦ
```

**Comment by jtauber** [comment]
The following are abbreviations for speakers:

```
Αγγ
Γρη
Μακ
Μαρ
Σως
Τρο
```

which I guess should be normalised to the full speaker name for this purpose.

**Comment by seumasjeltzz** [comment]
Right, I wonder if they should be all-caps in the text.

Also, are we going to run into a problem with Σοφία and σωφία?

**Comment by seumasjeltzz** [comment]
Everything on this list is a proper name, or else a speaker tag.

**Comment by jtauber** [comment]
I don't mind either way with the speaker tags but I might special-case them as they're also being flagged by my current code for not being accented.

By Σοφία and σωφία do you mean Σοφία (the proper name) and σοφία (the abstract noun)? There's no issue in terms of what it should be normalised to. The only issue might be my automated code might not always know which is meant at the start of a paragraph / direct speech or wherever else you decided to contextually capitalise.

For now, can I get away with just assuming Σοφία is always the proper name and σοφία the abstract noun? We can always support context-specific overrides if this isn't the case.

**Comment by seumasjeltzz** [comment]
re 3) For now, yes you can assume that. Not least because I haven't introduced σοφία as an abstract noun. 

special case speaker tags for now, that seems most workable for the present.
