### ISSUE TITLE
U+1FBF characters

### ISSUE THREAD

**Issue by jtauber** [seumasjeltzz/LinguaeGraecaePerSeIllustrata#29]
Running `text-validator` I got:

```
src/005.md:23:299:bad U+1FBF; consider replacing with U+2019
src/006.md:52:151:bad U+1FBF; consider replacing with U+2019
src/011.md:26:74:bad U+1FBF; consider replacing with U+2019
```

Two of these were reported in #8 (which was closed but they either weren't fixed or regressed).

**Comment by seumasjeltzz** [comment]
These should be corrected now. (I've also "updated" the way I type to hopefully avoid this particular issue.

I've updated 002 a fair bit, so worth re-running validator.
