### ISSUE TITLE
Correct to ὄγδοον

### ISSUE THREAD

**Issue by nevenjovanovic** [seumasjeltzz/LinguaeGraecaePerSeIllustrata#32]
The breathing is wrong in chapter title, should be ὄγδοον: https://github.com/seumasjeltzz/LinguaeGraecaePerSeIllustrata/blob/a2f03229064eb21679013304624b0f534beafe2a/docs/index.html#L34

**Comment by nevenjovanovic** [comment]
Should also be corrected in src/008.md

**Comment by nevenjovanovic** [comment]
And in https://github.com/seumasjeltzz/LinguaeGraecaePerSeIllustrata/blob/a2f03229064eb21679013304624b0f534beafe2a/docs/008.html#L11

**Comment by seumasjeltzz** [comment]
the html files are generated from the src ones (semi-manually). I've corrected the index and src/008.md
