### ISSUE TITLE
Grammar and usage in chapter 11

### ISSUE THREAD

**Issue by mortonsc** [seumasjeltzz/LinguaeGraecaePerSeIllustrata#34]
Reading through the chapters in a scattershot way, here are a few things I noticed in chapter 11:

1. End of paragraph 1:
> ὁ γὰρ οὗτός ἐστιν πιστός καὶ ἀγαθός.

Can't have ὁ without a substantive. Could be ὁ γὰρ δοῦλος οὗτος...

2. Midway through paragraph 2:
> σὺ μὲν νεός εἶ, γέρων δέ εἰμι.

I would normally expect the words contrasted with μέν / δέ to be parallel. A more natural rendering (to my ears at least) is σὺ μὲν νεὸς εἶ, ἐγὼ δὲ γέρων (εἰμί).

3. Later down in paragraph 2:
> μὴ ἀργὸς ἴσθι!

Maybe this is an Attic vs Koine thing (I've read more of the former), but I'm not sure I've EVER seen the imperative form ἴσθι of εἶναι outside of conjugation tables in textbooks. First alternative that comes to mind is μὴ ἀργῶς ἔχε.

4. Midway through paragraph 5:
> δὴ που βούλῃ ὅ τι;

I'm not sure what this sentence means, beyond what I can guess from context. Maybe there's an idiom I'm unfamiliar with? I don't know what sentence final ὃ τι would mean.

By the way, I'm quite happy to discover this project exists. I learned about it from a friend who's stuck in an intro to Greek course using Hansen & Quinn (ick!). Sooner or later I'll start sending pull requests with fixes to accents and other fiddly things.

**Comment by seumasjeltzz** [comment]
Hi Scott,

Just wanted to acknowledge that I've seen this and will work through the issues one by one.

**Comment by seumasjeltzz** [comment]
Okay, I've done the following:
1) I agree, I've modified this sentence
2) I agree that that is a standard way to parallel, but I've rephrased it slightly as you'll (eventually) see
3) I don't think imperative ἴσθι is super common, but this sentence has the precedence of Thales behind it
4) I've rewritten at δή που βούλῃ τι, which seems better. 

It will take a short time for this to get updated in the text (and even longer in the html version). 
Please do send through any other comments, they are much appreciated.
