### ISSUE TITLE
Missing letter in 002.md

### ISSUE THREAD

**Issue by peterfwhyte** [seumasjeltzz/LinguaeGraecaePerSeIllustrata#37]
In 002.md line beginning ἆρα Σωσίας υἱὸς τοῦ Γρηγορίου; near end of line εἰσὶ έσσαρα παιδία should be εἰσὶ **τ**έσσαρα παιδία.

**Comment by seumasjeltzz** [comment]
Thanks Peter, this has been corrected (among other things in 002) in today's update.
