### ISSUE TITLE
Extraneous colon?

### ISSUE THREAD

**Issue by peterfwhyte** [seumasjeltzz/LinguaeGraecaePerSeIllustrata#39]
In 002.md, penultimate paragraph of I, τίνος δοῦλός ἐστι Τροχίλος; : ὁ Τροχίλος τοῦ Γρηγορίου ἐστὶν δοῦλος. There seems to be a stray colon after the first question.

**Comment by seumasjeltzz** [comment]
Resolved in more recent updates.
