### ISSUE TITLE
Some questions about chapter 5

### ISSUE THREAD

**Issue by Mallioch** [seumasjeltzz/LinguaeGraecaePerSeIllustrata#4]
τοῦτό ἐστιν αὑτὴ πολλὰς δούλας ἔχει - Is that grammatically correct? You have two main verbs.
καὶ τί βούληται - why subjunctive? Perhaps you meant βούλεται?

**Comment by seumasjeltzz** [comment]
The first is conceptual; perhaps it needs a punctuation mark. "... that is, blah blah". Or perhaps I should stick a λέγειν in to finish of the τοῦτό ἐστιν phrase first.

The second one, yeah that is just a typo on my behalf, which perhaps I already corrected?

**Comment by Mallioch** [comment]
If you don't want to keep this issue around, feel free to close.

**Comment by seumasjeltzz** [comment]
I will. It's still open to remind me just to review it!

**Comment by seumasjeltzz** [comment]
After looking up τοῦτ᾿ ἐστιν, I think it's fine, so going to close this.
