### ISSUE TITLE
Chapter 9 typo - σπέμρα

### ISSUE THREAD

**Issue by qnoum** [seumasjeltzz/LinguaeGraecaePerSeIllustrata#40]
Chapter 9, part I, paragraph 2, sentence 3:
https://github.com/seumasjeltzz/LinguaeGraecaePerSeIllustrata/blob/master/src/009.md
".., ὁ δὲ δοῦλος τὸ σπέμρα σπέρει..."
σπέμρα should be σπέρμα.

**Comment by seumasjeltzz** [comment]
Thanks! Fixed in src now
