### ISSUE TITLE
character issues

### ISSUE THREAD

**Issue by jtauber** [seumasjeltzz/LinguaeGraecaePerSeIllustrata#8]
Discovered during writing tokenisation code as the first step to linguistic analysis tools:

* 001.md line 10: space before comma
* 001.mid line 19: should be hyphen not en-dash in –μος
* 004.md line 39: space before period
* 005.md line 23: τοῦτ᾿ should be a U+2019 not a U+1FBF
* 006.md line 52: τοῦτ᾿ should be a U+2019 not a U+1FBF 

and also:

* 004.md lines 5, 13, 46, 47: trailing whitespace
* 005.md lines 5, 6, 9, 10, 19, 21, 29, 35, 41, 54: trailing whitespace
* 006.md lines 9, 13, 16, 19, 26, 39, 47, 52: trailing whitespace

which don't cause any problems but many people have their editors set up to strip them on save so to avoid them accidentally checking in this change when contributing other changes, I'd suggest keeping the repo clean of trailing whitespace.

**Comment by ryanfb** [comment]
Just PR'd this—don't see the whitespace issues, so maybe they've already been fixed? Or my editor's betraying me?

**Comment by seumasjeltzz** [comment]
I think I may stripped them in my editor by changing settings, without processing this issue in particular.
